// -*- C++ -*-
//
// generated by wxGlade 1:1.1.1+repack on Sat Jan 17 13:37:37 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGNEWCONNECTION_H
#define DIALOGNEWCONNECTION_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
#include <wx/collpane.h>
// end wxGlade


class DialogNewConnection: public wxDialog {
public:
    // begin wxGlade: DialogNewConnection::ids
    // end wxGlade

    DialogNewConnection(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
    // begin wxGlade: DialogNewConnection::attributes
    wxTextCtrl* text_ctrl_vnc_server;
    wxTextCtrl* text_ctrl_vnc_port;
    wxPanel* panel_advanced;
    wxTextCtrl* text_ctrl_ssh_server;
    wxTextCtrl* text_ctrl_ssh_port;
    wxTextCtrl* text_ctrl_ssh_user;
    wxRadioButton* radio_btn_ssh_password;
    wxRadioButton* radio_btn_ssh_privkey;
    wxStaticText* label_ssh_password;
    wxTextCtrl* text_ctrl_ssh_password;
    wxButton* button_ssh_privkey_open;
    wxStaticText* label_ssh_privkey;
    wxStaticText* label_ssh_privkey_password;
    wxTextCtrl* text_ctrl_ssh_privkey_password;
    wxTextCtrl* text_ctrl_repeater_id;
    wxCollapsiblePane* coll_pane_advanced;
    wxButton* button_CANCEL;
    wxButton* button_OK;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGNEWCONNECTION_H
