// -*- C++ -*-
//
// generated by wxGlade 1:1.1.1+repack on Sat Jan 17 13:37:37 2026
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogNewConnection.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogNewConnection::DialogNewConnection(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: DialogNewConnection::DialogNewConnection
    wxBoxSizer* sizer_top = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_vnc_server_port = new wxFlexGridSizer(2, 2, 0, 0);
    sizer_top->Add(grid_sizer_vnc_server_port, 0, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 6);
    wxStaticText* label_vnc_server = new wxStaticText(this, wxID_ANY, _("VNC Server"));
    grid_sizer_vnc_server_port->Add(label_vnc_server, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_vnc_server = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    text_ctrl_vnc_server->SetToolTip(_("If using an SSH server, remember to correctly set the host to connect to above. For example, set it to localhost when the VNC server is on the same host as the SSH server."));
    grid_sizer_vnc_server_port->Add(text_ctrl_vnc_server, 0, wxALL|wxEXPAND, 6);
    wxStaticText* label_vnc_port = new wxStaticText(this, wxID_ANY, _("VNC Port"));
    grid_sizer_vnc_server_port->Add(label_vnc_port, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_vnc_port = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    text_ctrl_vnc_port->SetHint("5900");
    grid_sizer_vnc_server_port->Add(text_ctrl_vnc_port, 0, wxALL|wxEXPAND, 6);
    panel_advanced = new wxPanel(this, wxID_ANY);
    sizer_top->Add(panel_advanced, 0, wxEXPAND, 0);
    wxBoxSizer* sizer_advanced = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_ssh = new wxStaticBoxSizer(new wxStaticBox(panel_advanced, wxID_ANY, _("SSH Tunnel")), wxVERTICAL);
    sizer_advanced->Add(sizer_ssh, 0, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 6);
    wxFlexGridSizer* grid_sizer_ssh_server_port_user = new wxFlexGridSizer(3, 2, 0, 0);
    sizer_ssh->Add(grid_sizer_ssh_server_port_user, 0, wxEXPAND, 0);
    wxStaticText* label_ssh_server = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH Server"));
    grid_sizer_ssh_server_port_user->Add(label_ssh_server, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_server = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString);
    text_ctrl_ssh_server->SetToolTip(_("If using an SSH server, remember to correctly set the host to connect to above. For example, set it to localhost when the VNC server is on the same host as the SSH server."));
    grid_sizer_ssh_server_port_user->Add(text_ctrl_ssh_server, 0, wxALL|wxEXPAND, 6);
    wxStaticText* label_ssh_port = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH Port"));
    grid_sizer_ssh_server_port_user->Add(label_ssh_port, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_port = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString);
    text_ctrl_ssh_port->SetHint("22");
    grid_sizer_ssh_server_port_user->Add(text_ctrl_ssh_port, 0, wxALL|wxEXPAND, 6);
    wxStaticText* label_ssh_user = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH User"));
    grid_sizer_ssh_server_port_user->Add(label_ssh_user, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_user = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString);
    grid_sizer_ssh_server_port_user->Add(text_ctrl_ssh_user, 0, wxALL|wxEXPAND, 6);
    wxBoxSizer* sizer_ssh_password_privkey = new wxBoxSizer(wxHORIZONTAL);
    sizer_ssh->Add(sizer_ssh_password_privkey, 0, wxEXPAND, 0);
    radio_btn_ssh_password = new wxRadioButton(sizer_ssh->GetStaticBox(), wxID_ANY, _("Password"));
    radio_btn_ssh_password->SetValue(1);
    sizer_ssh_password_privkey->Add(radio_btn_ssh_password, 0, wxALL, 6);
    radio_btn_ssh_privkey = new wxRadioButton(sizer_ssh->GetStaticBox(), wxID_ANY, _("Private Key"));
    sizer_ssh_password_privkey->Add(radio_btn_ssh_privkey, 0, wxALL, 6);
    wxBoxSizer* sizer_ssh_password = new wxBoxSizer(wxHORIZONTAL);
    sizer_ssh->Add(sizer_ssh_password, 0, wxEXPAND, 0);
    label_ssh_password = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH Password"));
    sizer_ssh_password->Add(label_ssh_password, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_password = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    sizer_ssh_password->Add(text_ctrl_ssh_password, 1, wxALL|wxEXPAND, 6);
    wxFlexGridSizer* grid_sizer_ssh_privkey = new wxFlexGridSizer(2, 2, 0, 0);
    sizer_ssh->Add(grid_sizer_ssh_privkey, 0, wxEXPAND, 0);
    button_ssh_privkey_open = new wxButton(sizer_ssh->GetStaticBox(), wxID_ANY, _("Open Private Key"));
    button_ssh_privkey_open->Hide();
    grid_sizer_ssh_privkey->Add(button_ssh_privkey_open, 0, wxALL, 6);
    label_ssh_privkey = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("None selected"));
    label_ssh_privkey->Hide();
    grid_sizer_ssh_privkey->Add(label_ssh_privkey, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    label_ssh_privkey_password = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("Private Key Password"));
    label_ssh_privkey_password->Enable(0);
    label_ssh_privkey_password->Hide();
    grid_sizer_ssh_privkey->Add(label_ssh_privkey_password, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_privkey_password = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    text_ctrl_ssh_privkey_password->Enable(0);
    text_ctrl_ssh_privkey_password->Hide();
    grid_sizer_ssh_privkey->Add(text_ctrl_ssh_privkey_password, 1, wxALL|wxEXPAND, 6);
    wxStaticBoxSizer* sizer_repeater = new wxStaticBoxSizer(new wxStaticBox(panel_advanced, wxID_ANY, _("Repeater")), wxHORIZONTAL);
    sizer_advanced->Add(sizer_repeater, 1, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 6);
    wxStaticText* label_repeater_id = new wxStaticText(sizer_repeater->GetStaticBox(), wxID_ANY, _("Session ID"));
    sizer_repeater->Add(label_repeater_id, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_repeater_id = new wxTextCtrl(sizer_repeater->GetStaticBox(), wxID_ANY, wxEmptyString);
    sizer_repeater->Add(text_ctrl_repeater_id, 1, wxALL|wxEXPAND, 6);
    coll_pane_advanced = new wxCollapsiblePane(this, wxID_ANY, _("Advanced"));
    wxWindow *pane_win = coll_pane_advanced->GetPane();
    wxSizer *pane_sizer = new wxBoxSizer(wxVERTICAL);
    
    // previous code as set root as parent of panel_advanced, reparent
    panel_advanced->Reparent(pane_win);
    
    // previous code has attached panel_advanced there, detach and re-add to ours
    sizer_top->Detach(panel_advanced);
    pane_sizer->Add(panel_advanced, 1, wxGROW|wxALL, 0);
    
    pane_win->SetSizer(pane_sizer);
    pane_sizer->SetSizeHints(pane_win);
    sizer_top->Add(coll_pane_advanced, 0, wxALL|wxEXPAND, 12);
    wxStaticLine* static_line_1 = new wxStaticLine(this, wxID_ANY);
    sizer_top->Add(static_line_1, 0, wxEXPAND|wxLEFT|wxRIGHT, 12);
    wxBoxSizer* sizer_buttons = new wxBoxSizer(wxHORIZONTAL);
    sizer_top->Add(sizer_buttons, 0, wxALIGN_RIGHT|wxALL, 10);
    button_CANCEL = new wxButton(this, wxID_CANCEL, wxEmptyString);
    sizer_buttons->Add(button_CANCEL, 0, wxALL, 3);
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    sizer_buttons->Add(button_OK, 0, wxALL, 3);
    
    grid_sizer_ssh_privkey->AddGrowableCol(1);
    grid_sizer_ssh_server_port_user->AddGrowableCol(1);
    panel_advanced->SetSizer(sizer_advanced);
    grid_sizer_vnc_server_port->AddGrowableCol(1);
    SetSizer(sizer_top);
    sizer_top->Fit(this);
    SetAffirmativeId(button_OK->GetId());
    SetEscapeId(button_CANCEL->GetId());
    
    Layout();
    // end wxGlade
}

