// -*- C++ -*-
//
// generated by wxGlade 1:1.1.1+repack on Tue Dec 30 19:56:46 2025
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp `wx-config --cxxflags --libs` -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp `wx-config --cxxflags --libs` -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogNewConnection.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogNewConnection::DialogNewConnection(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: DialogNewConnection::DialogNewConnection
    wxBoxSizer* sizer_top = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_host = new wxStaticText(this, wxID_ANY, _("Enter host to connect to:"));
    sizer_top->Add(label_host, 0, wxALL, 12);
    text_ctrl_host = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    sizer_top->Add(text_ctrl_host, 0, wxEXPAND|wxLEFT|wxRIGHT, 18);
    panel_advanced = new wxPanel(this, wxID_ANY);
    sizer_top->Add(panel_advanced, 0, wxEXPAND, 0);
    wxBoxSizer* sizer_advanced = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_repeater = new wxStaticBoxSizer(new wxStaticBox(panel_advanced, wxID_ANY, _("Repeater")), wxVERTICAL);
    sizer_advanced->Add(sizer_repeater, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 12);
    wxStaticText* label_repeater_id = new wxStaticText(sizer_repeater->GetStaticBox(), wxID_ANY, _("If connecting to a repeater, enter the session ID here:"));
    sizer_repeater->Add(label_repeater_id, 0, wxALL, 6);
    text_ctrl_repeater_id = new wxTextCtrl(sizer_repeater->GetStaticBox(), wxID_ANY, wxEmptyString);
    sizer_repeater->Add(text_ctrl_repeater_id, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 12);
    wxStaticBoxSizer* sizer_ssh = new wxStaticBoxSizer(new wxStaticBox(panel_advanced, wxID_ANY, _("SSH Tunnel")), wxVERTICAL);
    sizer_advanced->Add(sizer_ssh, 0, wxEXPAND|wxLEFT|wxRIGHT, 12);
    wxFlexGridSizer* grid_sizer_ssh_server_port_user = new wxFlexGridSizer(3, 2, 0, 0);
    sizer_ssh->Add(grid_sizer_ssh_server_port_user, 0, wxEXPAND, 0);
    wxStaticText* label_ssh_server = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH Server"));
    grid_sizer_ssh_server_port_user->Add(label_ssh_server, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_server = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString);
    grid_sizer_ssh_server_port_user->Add(text_ctrl_ssh_server, 0, wxALL|wxEXPAND, 6);
    wxStaticText* label_ssh_port = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH Port"));
    grid_sizer_ssh_server_port_user->Add(label_ssh_port, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_port = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString);
    grid_sizer_ssh_server_port_user->Add(text_ctrl_ssh_port, 0, wxALL|wxEXPAND, 6);
    wxStaticText* label_ssh_user = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH User"));
    grid_sizer_ssh_server_port_user->Add(label_ssh_user, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_user = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString);
    grid_sizer_ssh_server_port_user->Add(text_ctrl_ssh_user, 0, wxALL|wxEXPAND, 6);
    wxBoxSizer* sizer_ssh_password_privkey = new wxBoxSizer(wxHORIZONTAL);
    sizer_ssh->Add(sizer_ssh_password_privkey, 0, wxEXPAND, 0);
    radio_btn_ssh_password = new wxRadioButton(sizer_ssh->GetStaticBox(), wxID_ANY, _("Password"));
    radio_btn_ssh_password->SetValue(1);
    sizer_ssh_password_privkey->Add(radio_btn_ssh_password, 0, wxALL, 6);
    radio_btn_ssh_privkey = new wxRadioButton(sizer_ssh->GetStaticBox(), wxID_ANY, _("Private Key"));
    sizer_ssh_password_privkey->Add(radio_btn_ssh_privkey, 0, wxALL, 6);
    wxBoxSizer* sizer_ssh_password = new wxBoxSizer(wxHORIZONTAL);
    sizer_ssh->Add(sizer_ssh_password, 0, wxEXPAND, 0);
    wxStaticText* label_ssh_password = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("SSH Password"));
    sizer_ssh_password->Add(label_ssh_password, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_password = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    sizer_ssh_password->Add(text_ctrl_ssh_password, 1, wxALL|wxEXPAND, 6);
    button_ssh_privkey_import = new wxButton(sizer_ssh->GetStaticBox(), wxID_ANY, _("Import Private Key"));
    button_ssh_privkey_import->Hide();
    sizer_ssh->Add(button_ssh_privkey_import, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 6);
    wxBoxSizer* sizer_ssh_privkey_password = new wxBoxSizer(wxHORIZONTAL);
    sizer_ssh->Add(sizer_ssh_privkey_password, 0, wxEXPAND, 0);
    wxStaticText* label_ssh_privkey_password = new wxStaticText(sizer_ssh->GetStaticBox(), wxID_ANY, _("Key Password"));
    label_ssh_privkey_password->Hide();
    sizer_ssh_privkey_password->Add(label_ssh_privkey_password, 0, wxALIGN_CENTER_VERTICAL|wxALL, 6);
    text_ctrl_ssh_privkey_password = new wxTextCtrl(sizer_ssh->GetStaticBox(), wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    text_ctrl_ssh_privkey_password->Hide();
    sizer_ssh_privkey_password->Add(text_ctrl_ssh_privkey_password, 1, wxALL|wxEXPAND, 6);
    coll_pane_advanced = new wxCollapsiblePane(this, wxID_ANY, _("Advanced"));
    wxWindow *pane_win = coll_pane_advanced->GetPane();
    wxSizer *pane_sizer = new wxBoxSizer(wxVERTICAL);
    
    // previous code as set root as parent of panel_advanced, reparent
    panel_advanced->Reparent(pane_win);
    
    // previous code has attached panel_advanced there, detach and re-add to ours
    sizer_top->Detach(panel_advanced);
    pane_sizer->Add(panel_advanced, 1, wxGROW|wxALL, 0);
    
    pane_win->SetSizer(pane_sizer);
    pane_sizer->SetSizeHints(pane_win);
    sizer_top->Add(coll_pane_advanced, 0, wxALL|wxEXPAND, 12);
    wxStaticLine* static_line_1 = new wxStaticLine(this, wxID_ANY);
    sizer_top->Add(static_line_1, 0, wxEXPAND|wxLEFT|wxRIGHT, 12);
    wxBoxSizer* sizer_buttons = new wxBoxSizer(wxHORIZONTAL);
    sizer_top->Add(sizer_buttons, 0, wxALIGN_RIGHT|wxALL, 10);
    button_CANCEL = new wxButton(this, wxID_CANCEL, wxEmptyString);
    sizer_buttons->Add(button_CANCEL, 0, wxALL, 3);
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    sizer_buttons->Add(button_OK, 0, wxALL, 3);
    
    grid_sizer_ssh_server_port_user->AddGrowableCol(1);
    panel_advanced->SetSizer(sizer_advanced);
    SetSizer(sizer_top);
    sizer_top->Fit(this);
    SetAffirmativeId(button_OK->GetId());
    SetEscapeId(button_CANCEL->GetId());
    
    Layout();
    // end wxGlade
}

