#ifndef EVTIDS_H
#define EVTIDS_H

enum
  {
    ID_TOOLBAR = wxID_HIGHEST + 42,
    ID_DISCOVERED,
    ID_BOOKMARKS,
    ID_STATISTICS,
    ID_FULLSCREEN,
    ID_STATS_SAVE_UPD_RAWBYTE,
    ID_STATS_SAVE_UPD_COUNT,
    ID_STATS_SAVE_LATENCIES,
    ID_STATS_SAVE_POINTER_LAT,
    ID_STATS_SAVE_LOSSRATIO,
    ID_STATS_SAVE_RECVBUF,
    ID_LISTBOX_SERVICES,
    ID_LISTBOX_BOOKMARKS,
    ID_WINDOWSHARE_PROC_END,
    ID_SEAMLESS_NORTH,
    ID_SEAMLESS_EAST,
    ID_SEAMLESS_SOUTH,
    ID_SEAMLESS_WEST,
    ID_SEAMLESS_DISABLED,
  };


#endif

