#ifndef EVTIDS_H
#define EVTIDS_H

enum
  {
    ID_TOOLBAR = wxID_HIGHEST + 42,
    ID_DISCOVERED,
    ID_BOOKMARKS,
    ID_STATISTICS,
    ID_FULLSCREEN,
    ID_STATS_SAVE_UPD,
    ID_STATS_SAVE_LAT,
    ID_STATS_SAVE_LOSSRATIO,
    ID_LISTBOX_SERVICES,
    ID_LISTBOX_BOOKMARKS,
    ID_WINDOWSHARE_PROC_END,
  };


#endif

